Default: &defaults
  database: Inter.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Inter_test.sqlite3
  <<: *defaults

Staging:
  database: Inter_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Inter_production.sqlite3
  poolsize: 100
  <<: *defaults
